### ISSUE TITLE
Access live data values from live data point

### ISSUE THREAD

**Issue by lbutler** [innovyze/Open-Source-Support#25]
In InfoWorks WS Pro I was hoping to access the live data values for local files using `get_live_data_values` however I'm pretty sure it only works for feeds based the class [WSLiveDataConfigNumbat](https://help.autodesk.com/view/IWWSPRO/2025/ENU/?guid=Innovyze_Exchange_Classes_WSPro_wslivedataconfignumbat_html)

With a bit of digging I can see there is another method `get_live_data` but I can't get it to do anything useful, plus its undocumented.

Is there any way to access live data stored in an SLI file or similar?[ Currently I'm manually parsing the files](https://github.com/modelcreate/model-calibrate/blob/master/public/modelcalibrate_export.rb#L486) but I was hoping to avoid that.

Is there anything I'm missing, or do I have to keep my figures crossed for it to be added in a future version?

**Comment by kmaschmann** [comment]
Hi @lbutler - I'll raise this with our developers to see what they have to say.

**Comment by DaveFace** [comment]
@lbutler Both methods only work with feeds, IIRC the get_live_data method dumps all the feeds from the Live Data Configuration object to CSV files. It was added for internal testing which is why it's undocumented, but for what it's worth the method signature is get_live_data(start_time, end_time, dir). 

Live data points are a bit of a legacy feature so I wouldn't expect them to be supported here, we're generally advising people move to feeds as they're now supported wherever live data points are (i.e. there's no need to create a proxy live data point for each one).

**Comment by lbutler** [comment]
Thanks @DaveFace for the info.

From what I understand, live data feeds are more associated with connections into telemetry systems while live data points are for flat files from devices like temporary loggers (or extracts from live systems).

In my use case I was trying to use the data during calibration which has many temporary loggers as SLI files, though ultimately I can still access this files on the hard drive so there will be work arounds.

Thanks again for the help!
