### ISSUE TITLE
Failed to import pollutant data

### ISSUE THREAD

**Issue by KillDragon** [innovyze/Open-Source-Support#3]
Dear expert，
When I used exchange to import pollutant data, I found that there was no problem with the code, but the imported data was lost in the software. Can you help me solve it？
The specific code is as follows：
```
begin
db=WSApplication.open('snumbat://localhost:40000/train03',false) 
object_path='>MODG~ModelGroup'
puts object_path
mo=db.model_object(object_path) 
#mo=mo.import_new_model_object(type,name,format,filepath,0)
name='ceshi'
b=mo.import_new_model_object('Pollutant graph',name,'COD',"C:\\temp\\p2_COD.csv",0)
b.import_data('BOD',"C:\\temp\\p2_BOD.csv")
puts 'success'
rescue 
puts "#{$!}"
end

```
![image](https://user-images.githubusercontent.com/15921876/141397017-a11e9311-9180-4184-bf5c-595109b659ba.png)

Thank you very much for taking the time to check my questions

**Comment by dfmore** [comment]
@KillDragon thanks for this question. The issue seems to be in line 8 of your code. The `import_new_model_object` method was set to read a `COD` file that is of the _InfoWorks file_ format. Such file would end with `*.cod` extension and has a specific structure. However, the method was set up to expect a `CSV` type file named `p2_COD.csv`. 

See the two export types below:
![image](https://user-images.githubusercontent.com/21298559/143873248-26741986-adab-4e37-bd2a-2b95a570727b.png)

I think you've since also submitted it as a support inquiry via our support portal and I've replied there. Apologies for the late reply here, it's still a learning curve for us using GitHub and we didn't have alerts set up for Issues yet.

**Comment by KillDragon** [comment]
Thank you for your reply
